import type { PromptExpectation } from "./types";

export const REGRESSION_PROMPTS: PromptExpectation[] = [
  {
    id: "P01",
    prompt: `A single-storey 5BHK residential bungalow on a 55ft x 50ft north-facing plot with total built-up area of 2600 sq ft. The main entrance is a 9ft x 6ft porch centered on the north wall leading into an 8ft x 7ft foyer. The living room is 17ft x 14ft in the northwest corner with a large north-facing window, flowing east into a 13ft x 11ft dining room which connects south into a 13ft x 11ft kitchen in the southeast zone. A 6ft x 5ft utility room sits behind the kitchen with a back door to the yard. The master bedroom is 15ft x 13ft in the southwest corner with an attached 9ft x 6ft ensuite bathroom and a 7ft x 5ft walk-in wardrobe. Bedroom 2 is 13ft x 11ft south-center with an attached 8ft x 5ft bathroom. Bedroom 3 is 12ft x 11ft southeast with a shared bathroom. Bedroom 4 is 12ft x 10ft east-center with window on east wall. Bedroom 5 is 11ft x 10ft northeast corner, doubles as guest room. A common bathroom 7ft x 5ft sits on the central hallway. A 4ft wide main hallway runs east-west connecting all bedrooms. All external walls 9 inches, internal walls 5 inches, all doors 3ft wide. Vastu compliant: entrance north, kitchen southeast, master southwest.`,
    vastu_required: true,
    plot: { width_ft: 55, depth_ft: 50, facing: "N" },
    expected_rooms: [
      { function: "porch", name_substring: "porch", dim_width_ft: 9, dim_depth_ft: 6, position_direction: "N" },
      { function: "foyer", name_substring: "foyer", dim_width_ft: 8, dim_depth_ft: 7 },
      { function: "living", name_substring: "living", dim_width_ft: 17, dim_depth_ft: 14, position_direction: "NW", must_have_window_on: "N" },
      { function: "dining", name_substring: "dining", dim_width_ft: 13, dim_depth_ft: 11 },
      { function: "kitchen", name_substring: "kitchen", dim_width_ft: 13, dim_depth_ft: 11, position_direction: "SE" },
      { function: "utility", name_substring: "utility", dim_width_ft: 6, dim_depth_ft: 5 },
      { function: "master_bedroom", name_substring: "master", dim_width_ft: 15, dim_depth_ft: 13, position_direction: "SW" },
      { function: "master_bathroom", name_substring: "ensuite", dim_width_ft: 9, dim_depth_ft: 6 },
      { function: "walk_in_wardrobe", name_substring: "wardrobe", dim_width_ft: 7, dim_depth_ft: 5 },
      { function: "bedroom", name_substring: "bedroom 2", dim_width_ft: 13, dim_depth_ft: 11, position_direction: "S" },
      { function: "bathroom", name_substring: "bathroom 2", dim_width_ft: 8, dim_depth_ft: 5 },
      { function: "bedroom", name_substring: "bedroom 3", dim_width_ft: 12, dim_depth_ft: 11, position_direction: "SE" },
      { function: "bedroom", name_substring: "bedroom 4", dim_width_ft: 12, dim_depth_ft: 10, position_direction: "E", must_have_window_on: "E" },
      { function: "bedroom", name_substring: "bedroom 5", dim_width_ft: 11, dim_depth_ft: 10, position_direction: "NE" },
      { function: "bathroom", name_substring: "common", dim_width_ft: 7, dim_depth_ft: 5 },
    ],
    forbidden_rooms: ["Drawing Room", "Verandah", "Walk-in Closet"],
    expected_pipeline: "B",
    expected_main_entrance_side: "N",
    expected_hallway_connects: ["master", "bedroom 2", "bedroom 3", "bedroom 4", "bedroom 5"],
    expected_windows: [
      { room: "living", wall: "N" },
      { room: "bedroom 4", wall: "E" },
    ],
  },
  {
    id: "P02",
    prompt: `5BHK villa on 50ft x 60ft east-facing plot, 2800 sqft, Vastu compliant. Master bedroom SW, kitchen SE, pooja NE, living room N. Five bedrooms total with attached bathrooms.`,
    vastu_required: true,
    plot: { width_ft: 50, depth_ft: 60, facing: "E" },
    expected_rooms: [
      { function: "master_bedroom", name_substring: "master", position_direction: "SW" },
      { function: "kitchen", name_substring: "kitchen", position_direction: "SE" },
      { function: "pooja", name_substring: "pooja", position_direction: "NE" },
      { function: "living", name_substring: "living", position_direction: "N" },
      { function: "bedroom", name_substring: "bedroom" },
    ],
    forbidden_rooms: [],
    expected_pipeline: "B",
  },
  {
    id: "P03",
    prompt: `Spacious 5BHK villa around 3000 sqft, modern open plan, double-height living, attached baths`,
    vastu_required: false,
    plot: null,
    expected_rooms: [
      { function: "living", name_substring: "living" },
      { function: "kitchen", name_substring: "kitchen" },
      { function: "master_bedroom", name_substring: "master" },
      { function: "bedroom", name_substring: "bedroom" },
      { function: "bathroom", name_substring: "bath" },
    ],
    forbidden_rooms: [],
    expected_pipeline: "A",
  },
  {
    id: "P04",
    prompt: `4BHK on 40ft x 60ft north-facing plot, 2200 sqft, Vastu compliant. Master 16ft x 14ft SW with attached 8ft x 6ft bath. Bedroom 2 13ft x 11ft NW. Bedroom 3 12ft x 11ft N. Bedroom 4 12ft x 10ft NE. Kitchen 12ft x 10ft SE. Living 18ft x 14ft N-center. Common bathroom 7ft x 5ft.`,
    vastu_required: true,
    plot: { width_ft: 40, depth_ft: 60, facing: "N" },
    expected_rooms: [
      { function: "master_bedroom", name_substring: "master", dim_width_ft: 16, dim_depth_ft: 14, position_direction: "SW" },
      { function: "master_bathroom", name_substring: "bath", dim_width_ft: 8, dim_depth_ft: 6 },
      { function: "bedroom", name_substring: "bedroom 2", dim_width_ft: 13, dim_depth_ft: 11, position_direction: "NW" },
      { function: "bedroom", name_substring: "bedroom 3", dim_width_ft: 12, dim_depth_ft: 11, position_direction: "N" },
      { function: "bedroom", name_substring: "bedroom 4", dim_width_ft: 12, dim_depth_ft: 10, position_direction: "NE" },
      { function: "kitchen", name_substring: "kitchen", dim_width_ft: 12, dim_depth_ft: 10, position_direction: "SE" },
      { function: "living", name_substring: "living", dim_width_ft: 18, dim_depth_ft: 14, position_direction: "N" },
    ],
    forbidden_rooms: ["Verandah", "Drawing Room"],
    expected_pipeline: "B",
  },
  {
    id: "P05",
    prompt: `4BHK Vastu compliant, 2000 sqft, plot facing east, kitchen southeast, master southwest`,
    vastu_required: true,
    plot: { width_ft: 0, depth_ft: 0, facing: "E" },
    expected_rooms: [
      { function: "master_bedroom", name_substring: "master", position_direction: "SW" },
      { function: "kitchen", name_substring: "kitchen", position_direction: "SE" },
      { function: "bedroom", name_substring: "bedroom" },
    ],
    forbidden_rooms: [],
    expected_pipeline: "B",
  },
  {
    id: "P06",
    prompt: `4BHK contemporary apartment 1800 sqft, large living-dining, modular kitchen, three bedrooms with attached baths plus master suite, study, balcony`,
    vastu_required: false,
    plot: null,
    expected_rooms: [
      { function: "living", name_substring: "living" },
      { function: "dining", name_substring: "dining" },
      { function: "kitchen", name_substring: "kitchen" },
      { function: "master_bedroom", name_substring: "master" },
      { function: "bedroom", name_substring: "bedroom" },
      { function: "study", name_substring: "study" },
      { function: "balcony", name_substring: "balcony" },
    ],
    forbidden_rooms: [],
    expected_pipeline: "A",
  },
  {
    id: "P07",
    prompt: `3BHK 1500 sqft on 35ft x 45ft north-facing plot. Master 14ft x 12ft SW. Bedroom 2 12ft x 10ft NW. Bedroom 3 11ft x 10ft N. Kitchen 10ft x 8ft SE. Living 16ft x 13ft NE. Pooja 5ft x 4ft NE. Vastu compliant.`,
    vastu_required: true,
    plot: { width_ft: 35, depth_ft: 45, facing: "N" },
    expected_rooms: [
      { function: "master_bedroom", name_substring: "master", dim_width_ft: 14, dim_depth_ft: 12, position_direction: "SW" },
      { function: "bedroom", name_substring: "bedroom 2", dim_width_ft: 12, dim_depth_ft: 10, position_direction: "NW" },
      { function: "bedroom", name_substring: "bedroom 3", dim_width_ft: 11, dim_depth_ft: 10, position_direction: "N" },
      { function: "kitchen", name_substring: "kitchen", dim_width_ft: 10, dim_depth_ft: 8, position_direction: "SE" },
      { function: "living", name_substring: "living", dim_width_ft: 16, dim_depth_ft: 13, position_direction: "NE" },
      { function: "pooja", name_substring: "pooja", dim_width_ft: 5, dim_depth_ft: 4, position_direction: "NE" },
    ],
    forbidden_rooms: ["Verandah"],
    expected_pipeline: "B",
  },
  {
    id: "P08",
    prompt: `3BHK 1400 sqft. Master bedroom 14ft x 12ft. Two more bedrooms 12ft x 10ft each. Living 16ft x 13ft, kitchen 10ft x 8ft, dining 10ft x 10ft, three bathrooms 5ft x 6ft, balcony 12ft x 4ft.`,
    vastu_required: false,
    plot: null,
    expected_rooms: [
      { function: "master_bedroom", name_substring: "master", dim_width_ft: 14, dim_depth_ft: 12 },
      { function: "bedroom", name_substring: "bedroom 2", dim_width_ft: 12, dim_depth_ft: 10 },
      { function: "bedroom", name_substring: "bedroom 3", dim_width_ft: 12, dim_depth_ft: 10 },
      { function: "living", name_substring: "living", dim_width_ft: 16, dim_depth_ft: 13 },
      { function: "kitchen", name_substring: "kitchen", dim_width_ft: 10, dim_depth_ft: 8 },
      { function: "dining", name_substring: "dining", dim_width_ft: 10, dim_depth_ft: 10 },
      { function: "balcony", name_substring: "balcony", dim_width_ft: 12, dim_depth_ft: 4 },
    ],
    forbidden_rooms: [],
    expected_pipeline: "B",
  },
  {
    id: "P09",
    prompt: `2BHK 900 sqft Vastu compliant, master southwest, kitchen southeast, north-facing entrance`,
    vastu_required: true,
    plot: { width_ft: 0, depth_ft: 0, facing: "N" },
    expected_rooms: [
      { function: "master_bedroom", name_substring: "master", position_direction: "SW" },
      { function: "kitchen", name_substring: "kitchen", position_direction: "SE" },
      { function: "bedroom", name_substring: "bedroom" },
    ],
    forbidden_rooms: [],
    expected_pipeline: "B",
  },
  {
    id: "P10",
    prompt: `Compact 2BHK 850 sqft, open plan living-kitchen, two bedrooms, two baths, balcony`,
    vastu_required: false,
    plot: null,
    expected_rooms: [
      { function: "living", name_substring: "living" },
      { function: "kitchen", name_substring: "kitchen" },
      { function: "bedroom", name_substring: "bedroom" },
      { function: "bathroom", name_substring: "bath" },
      { function: "balcony", name_substring: "balcony" },
    ],
    forbidden_rooms: [],
    expected_pipeline: "A",
  },
];
