import { describe, it, expect, vi, beforeAll } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { NextRequest } from "next/server";
import { REGRESSION_PROMPTS } from "./regression-prompts";
import { scoreAll } from "./scoring";
import type { PromptResult, SnapshotFile } from "./types";

// FLAG 1 mitigation: tests/setup.ts mocks OPENAI_API_KEY to a fake value,
// forcing programRoomsFallback (regex). To exercise the real AI pipeline,
// set OPENAI_API_KEY_REAL to a real sk- key in the environment. This
// beforeAll runs AFTER the global setup, so the override sticks.
beforeAll(() => {
  const real = process.env.OPENAI_API_KEY_REAL;
  if (real && real.startsWith("sk-")) {
    process.env.OPENAI_API_KEY = real;
    // eslint-disable-next-line no-console
    console.log("[harness] OPENAI_API_KEY_REAL detected — exercising real AI pipeline");
  } else {
    // eslint-disable-next-line no-console
    console.log("[harness] OPENAI_API_KEY_REAL not set — using mock key (regex fallback path)");
  }
});

vi.mock("@/lib/auth", () => ({
  auth: () =>
    Promise.resolve({
      user: {
        id: "regression-test-user",
        email: "vibecoders786@gmail.com",
        role: "PLATFORM_ADMIN",
        emailVerified: true,
      },
    }),
}));

vi.mock("@/lib/db", () => ({
  prisma: {
    workflow: {
      findFirst: vi.fn().mockResolvedValue({ id: "test-wf" }),
      create: vi.fn().mockResolvedValue({ id: "test-wf" }),
      update: vi.fn().mockResolvedValue({ id: "test-wf" }),
    },
    execution: {
      count: vi.fn().mockResolvedValue(0),
      create: vi.fn().mockResolvedValue({}),
    },
    user: {
      findUnique: vi.fn().mockResolvedValue({ emailVerified: true }),
    },
  },
}));

vi.mock("@/lib/rate-limit", () => ({
  checkEndpointRateLimit: vi.fn().mockResolvedValue({ success: true }),
  isAdminUser: vi.fn().mockReturnValue(true),
}));

const SNAPSHOT_NAME = process.env.SNAPSHOT_NAME ?? `snapshot-${Date.now()}`;
const SNAPSHOTS_DIR = path.join(__dirname, "snapshots");

function gitSha(): string | null {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
  } catch {
    return null;
  }
}

describe("Floor Plan Regression Suite", () => {
  it(
    "runs all 10 regression prompts and writes scorecard snapshot",
    async () => {
      const { POST } = await import("@/app/api/generate-floor-plan/route");
      const results: PromptResult[] = [];

      for (const expectation of REGRESSION_PROMPTS) {
        const start = Date.now();
        let project = null;
        let error: string | null = null;
        let pipelineUsed: string = "A";

        try {
          const req = new NextRequest("http://localhost/api/generate-floor-plan", {
            method: "POST",
            body: JSON.stringify({ prompt: expectation.prompt }),
            headers: { "Content-Type": "application/json" },
          });
          const res = await POST(req);
          const data = (await res.json()) as { project?: typeof project; error?: string; pipelineUsed?: string };
          if (data.error) error = data.error;
          if (data.project) project = data.project;
          pipelineUsed = data.pipelineUsed ?? "A";
        } catch (err) {
          error = err instanceof Error ? `${err.message}\n${err.stack?.split("\n").slice(0, 3).join("\n")}` : String(err);
        }

        const elapsed_ms = Date.now() - start;
        const score = project ? scoreAll(project, expectation) : null;

        results.push({
          id: expectation.id,
          prompt_summary: expectation.prompt.slice(0, 80).replace(/\s+/g, " "),
          elapsed_ms,
          error,
          pipeline_used: pipelineUsed,
          score,
          project,
        });
      }

      const scored = results.filter(r => r.score);
      const average = scored.length
        ? scored.reduce((s, r) => s + (r.score?.total ?? 0), 0) / scored.length
        : 0;

      // Strip the full FloorPlanProject from the committed snapshot — the diff
      // tool and human reviewers only need scores/components. Full projects can
      // be regenerated by re-running the harness; storing them in git would
      // bloat history by ~1MB per snapshot.
      const slimResults: PromptResult[] = results.map(r => ({ ...r, project: null }));
      const snapshot: SnapshotFile = {
        snapshot_name: SNAPSHOT_NAME,
        created_at: new Date().toISOString(),
        git_sha: gitSha(),
        results: slimResults,
        average,
      };

      if (!fs.existsSync(SNAPSHOTS_DIR)) fs.mkdirSync(SNAPSHOTS_DIR, { recursive: true });
      const snapshotPath = path.join(SNAPSHOTS_DIR, `${SNAPSHOT_NAME}.json`);
      fs.writeFileSync(snapshotPath, JSON.stringify(snapshot, null, 2));

      console.log("\n=== REGRESSION SCORECARD ===");
      const cols = ["ID", "TOTAL", "COMP", "VASTU", "DIM", "POS", "HAL", "GAP", "MS", "PIPE"];
      console.log(cols.map(c => c.padStart(7)).join(" "));
      for (const r of results) {
        if (!r.score) {
          console.log(`${r.id.padStart(7)} ERROR: ${r.error}`);
          continue;
        }
        const c = r.score.components;
        console.log(
          [
            r.id,
            r.score.total,
            c.completeness,
            c.vastu,
            c.dims,
            c.positions,
            c.hallucinations,
            c.gaps,
            r.elapsed_ms,
            r.pipeline_used,
          ]
            .map(v => String(v).padStart(7))
            .join(" "),
        );
      }
      console.log(`\nAVERAGE: ${average.toFixed(1)}/100`);
      console.log(`Snapshot: ${snapshotPath}`);

      expect(scored.length).toBeGreaterThan(0);
    },
    600_000,
  );
});
