-- ============================================================
-- KOS (Kalzen Operating System) — foundation migration (Week 1)
-- ============================================================
-- 10 tenant-scoped tables + 8 enums backing the white-labelled
-- Kalzen surface. The embedding column is declared as BYTEA here
-- (Prisma's default for `Unsupported("vector(1536)")`) — the
-- follow-up migration `kos_pgvector` installs the pgvector
-- extension and promotes the column to `vector(1536)`.
--
-- This file was hand-crafted instead of being generated by
-- `prisma migrate dev --create-only` because the live database
-- carries an applied migration (`20260504060354_add_user_utm_attribution`)
-- that is not present in this `migrations/` folder. The drift
-- means `prisma migrate dev` refuses to proceed without a
-- destructive reset. See `temp_folder/kos_week1_report.md` §8
-- for the reconciliation steps Govind must run before applying.
-- ============================================================

-- CreateEnum
CREATE TYPE "KosChannel" AS ENUM ('WHATSAPP', 'WEB');

-- CreateEnum
CREATE TYPE "KosLeadStage" AS ENUM ('INQUIRY', 'DRAWING_RECEIVED', 'BOQ_GENERATED', 'SITE_VISIT_SCHEDULED', 'COMMERCIAL_DISCUSSION', 'WON', 'LOST');

-- CreateEnum
CREATE TYPE "KosConversationStatus" AS ENUM ('BOT_ACTIVE', 'AWAITING_HUMAN', 'HUMAN_HANDLING', 'RESOLVED', 'CLOSED');

-- CreateEnum
CREATE TYPE "KosMessageDirection" AS ENUM ('INBOUND', 'OUTBOUND');

-- CreateEnum
CREATE TYPE "KosAuthorType" AS ENUM ('CUSTOMER', 'BOT', 'BD_HUMAN', 'SYSTEM');

-- CreateEnum
CREATE TYPE "KosDocType" AS ENUM ('PAC', 'CERTIFICATE', 'CASE_STUDY', 'PRICING', 'COMPARISON', 'FAQ', 'WARRANTY', 'OTHER');

-- CreateEnum
CREATE TYPE "KosDocStatus" AS ENUM ('UPLOADED', 'PARSING', 'CHUNKING', 'EMBEDDING', 'READY', 'FAILED');

-- CreateEnum
CREATE TYPE "KosBdRole" AS ENUM ('BD', 'OPERATIONS', 'VIEWER', 'TENANT_ADMIN');

-- CreateTable
CREATE TABLE "kos_tenants" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "customDomain" TEXT,
    "branding" JSONB NOT NULL,
    "whatsappConfig" JSONB,
    "frappeConfig" JSONB,
    "s3Config" JSONB,
    "featureFlags" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "kos_tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_customers" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "firstSeenChannel" "KosChannel" NOT NULL,
    "frappeLeadId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "kos_customers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_bd_users" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "name" TEXT NOT NULL,
    "role" "KosBdRole" NOT NULL DEFAULT 'BD',
    "passwordHash" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastLoginAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_bd_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_documents" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "docType" "KosDocType" NOT NULL,
    "s3Key" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "pageCount" INTEGER,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "KosDocStatus" NOT NULL DEFAULT 'UPLOADED',
    "indexedAt" TIMESTAMP(3),
    "uploadedBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_document_chunks" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "pageNum" INTEGER,
    "chunkIndex" INTEGER NOT NULL,
    "embedding" BYTEA NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_document_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_conversations" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "customerId" TEXT,
    "anonymousSessionId" TEXT,
    "channel" "KosChannel" NOT NULL,
    "stage" "KosLeadStage" NOT NULL DEFAULT 'INQUIRY',
    "status" "KosConversationStatus" NOT NULL DEFAULT 'BOT_ACTIVE',
    "assignedBdUserId" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastMessageAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "kos_conversations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_messages" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "direction" "KosMessageDirection" NOT NULL,
    "channel" "KosChannel" NOT NULL,
    "authorType" "KosAuthorType" NOT NULL,
    "authorId" TEXT,
    "content" TEXT NOT NULL,
    "mediaUrl" TEXT,
    "mediaType" TEXT,
    "whatsappMessageId" TEXT,
    "citations" JSONB,
    "llmMetadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_audit_logs" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "conversationId" TEXT,
    "actorType" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "details" JSONB,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_otp_requests" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "codeHash" TEXT NOT NULL,
    "anonymousSessionId" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "verifiedAt" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_otp_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kos_magic_links" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "consumedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kos_magic_links_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "kos_tenants_slug_key" ON "kos_tenants"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "kos_tenants_customDomain_key" ON "kos_tenants"("customDomain");

-- CreateIndex
CREATE INDEX "kos_tenants_slug_idx" ON "kos_tenants"("slug");

-- CreateIndex
CREATE INDEX "kos_tenants_customDomain_idx" ON "kos_tenants"("customDomain");

-- CreateIndex
CREATE UNIQUE INDEX "kos_customers_frappeLeadId_key" ON "kos_customers"("frappeLeadId");

-- CreateIndex
CREATE INDEX "kos_customers_phone_idx" ON "kos_customers"("phone");

-- CreateIndex
CREATE INDEX "kos_customers_frappeLeadId_idx" ON "kos_customers"("frappeLeadId");

-- CreateIndex
CREATE UNIQUE INDEX "kos_customers_tenantId_phone_key" ON "kos_customers"("tenantId", "phone");

-- CreateIndex
CREATE UNIQUE INDEX "kos_bd_users_tenantId_email_key" ON "kos_bd_users"("tenantId", "email");

-- CreateIndex
CREATE INDEX "kos_documents_tenantId_docType_idx" ON "kos_documents"("tenantId", "docType");

-- CreateIndex
CREATE INDEX "kos_documents_tenantId_status_idx" ON "kos_documents"("tenantId", "status");

-- CreateIndex
CREATE INDEX "kos_document_chunks_documentId_idx" ON "kos_document_chunks"("documentId");

-- CreateIndex
CREATE INDEX "kos_conversations_tenantId_customerId_idx" ON "kos_conversations"("tenantId", "customerId");

-- CreateIndex
CREATE INDEX "kos_conversations_tenantId_status_idx" ON "kos_conversations"("tenantId", "status");

-- CreateIndex
CREATE INDEX "kos_conversations_anonymousSessionId_idx" ON "kos_conversations"("anonymousSessionId");

-- CreateIndex
CREATE UNIQUE INDEX "kos_messages_whatsappMessageId_key" ON "kos_messages"("whatsappMessageId");

-- CreateIndex
CREATE INDEX "kos_messages_conversationId_createdAt_idx" ON "kos_messages"("conversationId", "createdAt");

-- CreateIndex
CREATE INDEX "kos_messages_whatsappMessageId_idx" ON "kos_messages"("whatsappMessageId");

-- CreateIndex
CREATE INDEX "kos_audit_logs_tenantId_createdAt_idx" ON "kos_audit_logs"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "kos_audit_logs_conversationId_idx" ON "kos_audit_logs"("conversationId");

-- CreateIndex
CREATE INDEX "kos_otp_requests_tenantId_phone_idx" ON "kos_otp_requests"("tenantId", "phone");

-- CreateIndex
CREATE INDEX "kos_otp_requests_expiresAt_idx" ON "kos_otp_requests"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "kos_magic_links_tokenHash_key" ON "kos_magic_links"("tokenHash");

-- CreateIndex
CREATE INDEX "kos_magic_links_tokenHash_idx" ON "kos_magic_links"("tokenHash");

-- CreateIndex
CREATE INDEX "kos_magic_links_expiresAt_idx" ON "kos_magic_links"("expiresAt");

-- AddForeignKey
ALTER TABLE "kos_customers" ADD CONSTRAINT "kos_customers_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "kos_tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_bd_users" ADD CONSTRAINT "kos_bd_users_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "kos_tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_documents" ADD CONSTRAINT "kos_documents_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "kos_tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_document_chunks" ADD CONSTRAINT "kos_document_chunks_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "kos_documents"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_conversations" ADD CONSTRAINT "kos_conversations_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "kos_tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_conversations" ADD CONSTRAINT "kos_conversations_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "kos_customers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_conversations" ADD CONSTRAINT "kos_conversations_assignedBdUserId_fkey" FOREIGN KEY ("assignedBdUserId") REFERENCES "kos_bd_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kos_messages" ADD CONSTRAINT "kos_messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "kos_conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
