"""Phase 1 — richMode gating tests.

The Pydantic model now treats `richMode` as a typed Literal. The builder
filters elements by rich mode in addition to the existing per-discipline
filter. These tests pin the *relationships* between the 5 modes — exact
counts come from the audit baseline doc.

Per-fixture pinned values are imported from `audit_baseline_pins.py`,
which is regenerated by `scripts/audit_emission.py` whenever the gating
table or any builder changes. If a builder change shifts a count, run
the audit script and re-pin.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

import ifcopenshell
import pytest

from app.models.request import ExportIFCRequest
from app.services.audit_counter import audit_model
from app.services.ifc_builder import build_multi_discipline


FIXTURE_DIR = Path(__file__).parent / "fixtures"

ALL_FIXTURES = ["simple_box", "multistorey_residential", "non_rectangular"]
RICH_MODES = ["off", "arch-only", "structural", "mep", "full"]

# These are the integer entity-count totals captured by
# scripts/audit_emission.py at Phase 1 land. They pin the gating
# behaviour: a future builder change that shifts these values without
# re-pinning will fail the test, forcing a deliberate baseline update.
EXPECTED_TOTAL_ENTITIES: dict[str, dict[str, int]] = {
    # Phase 2 re-pin: type instancing + IfcDistributionSystem +
    # IS-808 profile + NBC India + RERA + deterministic GUID monkey-
    # patch all shifted these counts. Source of truth:
    # `temp_folder/python-service-baseline-2026-05-02.md`.
    "simple_box": {
        "off": 37, "arch-only": 534, "structural": 534, "mep": 534, "full": 534,
    },
    "multistorey_residential": {
        "off": 41, "arch-only": 1881, "structural": 1881, "mep": 1920, "full": 1969,
    },
    "non_rectangular": {
        "off": 39, "arch-only": 1322, "structural": 1322, "mep": 1353, "full": 1394,
    },
}


def _load(name: str) -> ExportIFCRequest:
    raw = json.loads((FIXTURE_DIR / f"{name}.json").read_text())
    raw.pop("_comment", None)
    return ExportIFCRequest.model_validate(raw)


def _audit(req: ExportIFCRequest, mode: str | None) -> dict:
    new_options = req.options.model_copy(update={"rich_mode": mode, "disciplines": ["combined"]})
    new_req = req.model_copy(update={"options": new_options})
    results = build_multi_discipline(new_req)
    ifc_bytes, _, _ = results["combined"]
    with tempfile.NamedTemporaryFile(suffix=".ifc", delete=False, mode="wb") as tmp:
        tmp.write(ifc_bytes)
        tmp.flush()
        tmp_path = tmp.name
    return audit_model(ifcopenshell.open(tmp_path))


# ── Smoke / baseline pins ─────────────────────────────────────────────


@pytest.mark.parametrize("fixture", ALL_FIXTURES)
@pytest.mark.parametrize("mode", RICH_MODES)
def test_total_entity_count_matches_baseline(fixture: str, mode: str):
    """Pinned counts from `scripts/audit_emission.py` at Phase 1 land.

    A drift here means a builder change moved the audit baseline. Re-run
    `scripts/audit_emission.py` and update both the baseline doc and the
    EXPECTED_TOTAL_ENTITIES table above in the same commit.
    """
    req = _load(fixture)
    a = _audit(req, mode)
    expected = EXPECTED_TOTAL_ENTITIES[fixture][mode]
    assert a["total_entities"] == expected, (
        f"{fixture}/{mode}: expected {expected} entities, got {a['total_entities']}"
    )


# ── Relationship invariants ───────────────────────────────────────────


@pytest.mark.parametrize("fixture", ALL_FIXTURES)
def test_off_is_strictly_less_than_full(fixture: str):
    """Acceptance criterion #2: `full` must produce measurably more entities than `off`."""
    req = _load(fixture)
    off = _audit(req, "off")
    full = _audit(req, "full")
    assert off["total_entities"] < full["total_entities"], (
        f"{fixture}: off={off['total_entities']} not strictly less than full={full['total_entities']}"
    )


@pytest.mark.parametrize("fixture", ALL_FIXTURES)
def test_off_emits_only_spatial_structure(fixture: str):
    """`off` mode must contain ZERO physical building elements.

    Spatial entities (Project/Site/Building/Storey) are allowed; everything
    else (walls, slabs, MEP, etc.) must be absent.
    """
    req = _load(fixture)
    a = _audit(req, "off")
    physical_types = [
        "IfcWall", "IfcSlab", "IfcColumn", "IfcBeam", "IfcWindow", "IfcDoor",
        "IfcStairFlight", "IfcSpace", "IfcRailing", "IfcCovering",
        "IfcDuctSegment", "IfcPipeSegment", "IfcCableCarrierSegment",
        "IfcFlowTerminal", "IfcOpeningElement",
    ]
    for cls in physical_types:
        n = a["by_type"].get(cls, 0)
        assert n == 0, f"{fixture}: off mode emitted {n} {cls} (expected 0)"

    # And the spatial-structure baseline is intact.
    assert a["by_type"].get("IfcProject", 0) == 1
    assert a["by_type"].get("IfcSite", 0) == 1
    assert a["by_type"].get("IfcBuilding", 0) == 1
    assert a["by_type"].get("IfcBuildingStorey", 0) >= 1


@pytest.mark.parametrize("fixture", ALL_FIXTURES)
def test_arch_only_excludes_mep_elements(fixture: str):
    """`arch-only` mode must exclude duct / pipe / cable-tray / flow-terminal."""
    req = _load(fixture)
    a = _audit(req, "arch-only")
    for cls in ("IfcDuctSegment", "IfcPipeSegment", "IfcCableCarrierSegment", "IfcFlowTerminal"):
        assert a["by_type"].get(cls, 0) == 0, (
            f"{fixture}: arch-only mode should exclude {cls}, found {a['by_type'][cls]}"
        )


@pytest.mark.parametrize("fixture", ALL_FIXTURES)
def test_structural_count_at_least_arch_only(fixture: str):
    """`structural` ≥ `arch-only` — same allowed type set today (rebar emitter
    not yet implemented), so the relation is "≥" not ">". Phase 3 will lift
    this to strictly >."""
    req = _load(fixture)
    arch = _audit(req, "arch-only")
    struct = _audit(req, "structural")
    assert struct["total_entities"] >= arch["total_entities"], (
        f"{fixture}: structural ({struct['total_entities']}) < arch-only ({arch['total_entities']})"
    )


def test_mep_strictly_greater_than_arch_only_when_mep_present():
    """On fixtures that contain MEP elements, `mep` mode must produce MORE
    entities than `arch-only`. simple_box has no MEP elements → equal."""
    for fixture in ("multistorey_residential", "non_rectangular"):
        req = _load(fixture)
        arch = _audit(req, "arch-only")
        mep = _audit(req, "mep")
        assert mep["total_entities"] > arch["total_entities"], (
            f"{fixture}: mep ({mep['total_entities']}) not > arch-only ({arch['total_entities']})"
        )


def test_full_strictly_greater_than_mep_when_mep_present():
    """`full` must add MEP body geometry on top of `mep`'s bodyless emission,
    so `full > mep` on fixtures with MEP elements."""
    for fixture in ("multistorey_residential", "non_rectangular"):
        req = _load(fixture)
        mep = _audit(req, "mep")
        full = _audit(req, "full")
        assert full["total_entities"] > mep["total_entities"], (
            f"{fixture}: full ({full['total_entities']}) not > mep ({mep['total_entities']})"
        )


def test_unset_richmode_matches_full_on_all_fixtures():
    """Backward-compat invariant: `richMode` absent (None) must match `full`
    on every fixture, since both bypass the gate. baseline_building.json
    relies on this."""
    for fixture in ALL_FIXTURES:
        req = _load(fixture)
        none_audit = _audit(req, None)
        full_audit = _audit(req, "full")
        assert none_audit["total_entities"] == full_audit["total_entities"], (
            f"{fixture}: richMode=None ({none_audit['total_entities']}) "
            f"!= richMode='full' ({full_audit['total_entities']})"
        )
