-- ============================================================
-- KOS Week 2 — KosBdSession table
-- ============================================================
-- BD console multi-device sign-in. One row per active session, the
-- raw token (`${bdUserId}.${base64url(randomBytes(32))}`) lives only
-- in the HttpOnly cookie; the DB stores its bcrypt(12) hash.
--
-- Hand-crafted (instead of generated by `prisma migrate dev
-- --create-only`) for the same drift reason documented in
-- `20260518000000_kos_foundation_week1`: the dev DB carries
-- `20260504060354_add_user_utm_attribution` which the local migrations
-- folder lacks, so `prisma migrate dev` refuses without a reset.
-- ============================================================

-- CreateTable
CREATE TABLE "kos_bd_sessions" (
    "id" TEXT NOT NULL,
    "bdUserId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "userAgent" TEXT,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMP(3),

    CONSTRAINT "kos_bd_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "kos_bd_sessions_tokenHash_key" ON "kos_bd_sessions"("tokenHash");

-- CreateIndex
CREATE INDEX "kos_bd_sessions_tokenHash_idx" ON "kos_bd_sessions"("tokenHash");

-- CreateIndex
CREATE INDEX "kos_bd_sessions_bdUserId_idx" ON "kos_bd_sessions"("bdUserId");

-- CreateIndex
CREATE INDEX "kos_bd_sessions_expiresAt_idx" ON "kos_bd_sessions"("expiresAt");

-- AddForeignKey
ALTER TABLE "kos_bd_sessions"
    ADD CONSTRAINT "kos_bd_sessions_bdUserId_fkey"
    FOREIGN KEY ("bdUserId") REFERENCES "kos_bd_users"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
