/**
 * 5I PR 4 — Formwork JSON → PDF (.pdf) renderer.
 *
 * Consumes a `FormworkOutput` (15 top-level keys per PR 2a's capture —
 * no `commercial_terms` by design) and produces a multi-page A4 PDF:
 *
 *   Page 1   — Cover (project name + drawing meta + Formwork ID)
 *   Page 2   — Summary (tier_1 — props/walers/kickers/...)
 *   Page 3+  — Categories (tier_2_categories dict)
 *   Page N+  — Components (tier_6_components array)
 *   Last     — Warnings & Pending Karthik
 *
 * Defensive: missing fields render "N/A" or "No data" — never throws.
 * Page-overflow safe: `ensureSpace()` adds a new page when content
 * would clip the bottom margin.
 *
 * Mirrors `src/services/pdf-report-server.ts` for jsPDF idioms:
 * `new jsPDF({orientation:"portrait", unit:"mm", format:"a4"})`,
 * `doc.text(text, x, y, {align})`, `doc.setFont/setFontSize/setTextColor`,
 * `doc.output("arraybuffer")` → Buffer.
 */

import { jsPDF } from "jspdf";
import type { KosCustomerDrawing } from "@prisma/client";

import { kosLog } from "@/features/kos/lib/kos-logger";
import type { FormworkOutput } from "@/features/kos/types/sidecar";

export interface RenderFormworkPdfArgs {
  formwork: FormworkOutput;
  drawing: KosCustomerDrawing;
  /** Same discriminated envelope as the BOQ renderer. Optional. */
  parseResult?: unknown;
}

const MARGIN_MM = 20;
const LINE_HEIGHT_MM = 7;
const FOOTER_OFFSET = 10;

export async function renderFormworkPdf(args: RenderFormworkPdfArgs): Promise<Buffer> {
  const startedAt = Date.now();

  kosLog.info("kos_formwork_render_start", {
    drawingId: args.drawing.id,
    formworkId: args.formwork?.formwork_id,
  });

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const titleBlock = extractTitleBlock(args.parseResult);
  const projectName =
    titleBlock?.project_name ?? args.drawing.originalFilename ?? "Untitled";

  // ── Page 1: Cover ───────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(20, 50, 35);
  doc.text("Formwork Quantities", pageWidth / 2, 55, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text(projectName, pageWidth / 2, 75, { align: "center", maxWidth: pageWidth - MARGIN_MM * 2 });

  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  let coverY = 105;
  for (const [label, value] of [
    ["Drawing Number", titleBlock?.drawing_number ?? "N/A"],
    ["Revision", titleBlock?.revision ?? "N/A"],
    ["Formwork ID", args.formwork.formwork_id ?? "N/A"],
    ["Generated", args.formwork.generated_at ?? "N/A"],
    ["Schema Version", args.formwork.schema_version ?? "N/A"],
  ] as [string, string][]) {
    doc.text(`${label}:`, MARGIN_MM, coverY);
    doc.text(String(value ?? "N/A"), 75, coverY);
    coverY += 8;
  }

  // Cover footer
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Generated by Kalzen Operating System",
    pageWidth / 2,
    pageHeight - 15,
    { align: "center" },
  );

  // ── Helpers ────────────────────────────────────────────────────────
  const startSection = (title: string): number => {
    doc.addPage();
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(projectName, MARGIN_MM, 15, {
      maxWidth: pageWidth - MARGIN_MM * 2,
    });
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(title, MARGIN_MM, 30);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    return 45;
  };

  const ensureSpace = (currentY: number, needed: number, sectionTitle: string): number => {
    if (currentY + needed > pageHeight - 25) {
      return startSection(`${sectionTitle} (continued)`);
    }
    return currentY;
  };

  const writeLabelValue = (y: number, label: string, value: string | number | null): number => {
    doc.text(`${label}:`, MARGIN_MM, y);
    const val = value == null ? "N/A" : String(value);
    doc.text(val, 90, y);
    return y + LINE_HEIGHT_MM;
  };

  // ── Page 2: Summary ─────────────────────────────────────────────────
  let y = startSection("Summary");
  const summary = (args.formwork.tier_1_summary ?? {}) as Record<string, unknown>;
  const summaryFields: [string, string][] = [
    ["Total Props", "total_props"],
    ["Props (L)", "props_l_count"],
    ["Props (M)", "props_m_count"],
    ["Props (H)", "props_h_count"],
    ["Props (XH)", "props_xh_count"],
    ["Total Walers", "total_walers"],
    ["Total Kickers", "total_kickers"],
    ["Raker Props", "raker_props_count"],
    ["Diagonal Braces", "diagonal_braces_count"],
    ["Starter Track Metres", "total_starter_track_meters"],
  ];

  let printed = 0;
  for (const [label, key] of summaryFields) {
    const v = summary[key];
    if (v == null) continue;
    y = ensureSpace(y, LINE_HEIGHT_MM, "Summary");
    y = writeLabelValue(y, label, pickNumberOrString(v));
    printed += 1;
  }
  if (printed === 0) {
    doc.text("No summary data available.", MARGIN_MM, y);
  }

  // ── Categories (tier_2_categories dict) ────────────────────────────
  y = startSection("Categories");
  const categories = args.formwork.tier_2_categories;
  if (!categories || typeof categories !== "object" || Array.isArray(categories)) {
    doc.text("No category data available.", MARGIN_MM, y);
  } else {
    const entries = Object.entries(categories as Record<string, unknown>);
    if (entries.length === 0) {
      doc.text("No category data available.", MARGIN_MM, y);
    } else {
      for (const [name, value] of entries) {
        y = ensureSpace(y, LINE_HEIGHT_MM * 2, "Categories");
        doc.setFont("helvetica", "bold");
        doc.text(name, MARGIN_MM, y);
        doc.setFont("helvetica", "normal");
        y += LINE_HEIGHT_MM;
        if (value && typeof value === "object" && !Array.isArray(value)) {
          for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
            y = ensureSpace(y, LINE_HEIGHT_MM, "Categories");
            y = writeLabelValue(y, `  ${k}`, pickNumberOrString(v));
          }
        } else {
          y = writeLabelValue(y, "  value", pickNumberOrString(value));
        }
      }
    }
  }

  // ── Components (tier_6_components) — first 50 to keep PDF reasonable ─
  y = startSection("Components");
  const components = safeArr(args.formwork.tier_6_components);
  if (components.length === 0) {
    doc.text("No component data available.", MARGIN_MM, y);
  } else {
    doc.text(`${components.length} components (showing first 50)`, MARGIN_MM, y);
    y += LINE_HEIGHT_MM + 2;
    const headers = ["SKU", "Type", "Count", "Length mm"];
    doc.setFont("helvetica", "bold");
    drawRow(doc, y, [headers[0], headers[1], headers[2], headers[3]]);
    doc.setFont("helvetica", "normal");
    y += LINE_HEIGHT_MM;

    for (let i = 0; i < Math.min(components.length, 50); i++) {
      const item = components[i];
      if (!item || typeof item !== "object") continue;
      const obj = item as Record<string, unknown>;
      y = ensureSpace(y, LINE_HEIGHT_MM, "Components");
      drawRow(doc, y, [
        String(pickField(obj, ["sku", "sku_code", "code"]) ?? "—"),
        String(pickField(obj, ["type", "component_type", "kind"]) ?? "—"),
        String(pickField(obj, ["count", "quantity"]) ?? "—"),
        String(pickField(obj, ["length_mm", "length"]) ?? "—"),
      ]);
      y += LINE_HEIGHT_MM;
    }
    if (components.length > 50) {
      y = ensureSpace(y, LINE_HEIGHT_MM, "Components");
      doc.text(`… and ${components.length - 50} more (see full data in companion Excel)`, MARGIN_MM, y);
    }
  }

  // ── Warnings & Pending ─────────────────────────────────────────────
  y = startSection("Warnings & Pending Items");

  const warnings = safeArr(args.formwork.warnings);
  const assumptions = safeArr(args.formwork.assumptions_made);
  const pending = safeArr(args.formwork.pending_karthik);

  if (warnings.length + assumptions.length + pending.length === 0) {
    doc.text("No warnings, assumptions, or pending items.", MARGIN_MM, y);
  } else {
    if (warnings.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.text("Warnings", MARGIN_MM, y);
      doc.setFont("helvetica", "normal");
      y += LINE_HEIGHT_MM;
      for (const w of warnings) {
        y = ensureSpace(y, LINE_HEIGHT_MM, "Warnings & Pending Items");
        const lines = doc.splitTextToSize(`• ${String(w)}`, pageWidth - MARGIN_MM * 2);
        doc.text(lines, MARGIN_MM, y);
        y += lines.length * (LINE_HEIGHT_MM - 1);
      }
      y += 3;
    }
    if (assumptions.length > 0) {
      y = ensureSpace(y, LINE_HEIGHT_MM * 2, "Warnings & Pending Items");
      doc.setFont("helvetica", "bold");
      doc.text("Assumptions", MARGIN_MM, y);
      doc.setFont("helvetica", "normal");
      y += LINE_HEIGHT_MM;
      for (const a of assumptions) {
        y = ensureSpace(y, LINE_HEIGHT_MM, "Warnings & Pending Items");
        const lines = doc.splitTextToSize(`• ${String(a)}`, pageWidth - MARGIN_MM * 2);
        doc.text(lines, MARGIN_MM, y);
        y += lines.length * (LINE_HEIGHT_MM - 1);
      }
      y += 3;
    }
    if (pending.length > 0) {
      y = ensureSpace(y, LINE_HEIGHT_MM * 2, "Warnings & Pending Items");
      doc.setFont("helvetica", "bold");
      doc.text("Pending Karthik review", MARGIN_MM, y);
      doc.setFont("helvetica", "normal");
      y += LINE_HEIGHT_MM;
      for (const p of pending) {
        y = ensureSpace(y, LINE_HEIGHT_MM, "Warnings & Pending Items");
        const lines = doc.splitTextToSize(`• ${jsonOneLine(p)}`, pageWidth - MARGIN_MM * 2);
        doc.text(lines, MARGIN_MM, y);
        y += lines.length * (LINE_HEIGHT_MM - 1);
      }
    }
  }

  // ── Page numbers + footers on every page after cover ───────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - MARGIN_MM,
      pageHeight - FOOTER_OFFSET,
      { align: "right" },
    );
    doc.text(
      "Kalzen Operating System",
      pageWidth / 2,
      pageHeight - FOOTER_OFFSET,
      { align: "center" },
    );
  }

  // Output
  const arrayBuffer = doc.output("arraybuffer");
  const buffer = Buffer.from(arrayBuffer);
  const durationMs = Date.now() - startedAt;

  kosLog.info("kos_formwork_render_done", {
    drawingId: args.drawing.id,
    formworkId: args.formwork?.formwork_id,
    bytes: buffer.byteLength,
    pages: totalPages,
    durationMs,
  });

  return buffer;
}

// ── Helpers ────────────────────────────────────────────────────────────

interface TitleBlockShape {
  project_name?: string | null;
  drawing_number?: string | null;
  revision?: string | null;
}

function extractTitleBlock(parseResult: unknown): TitleBlockShape | null {
  if (!parseResult || typeof parseResult !== "object") return null;
  const pr = parseResult as { kind?: unknown; data?: unknown };
  if (pr.kind !== "parser") return null;
  const data = pr.data;
  if (!data || typeof data !== "object") return null;
  const tb = (data as { title_block?: unknown }).title_block;
  if (!tb || typeof tb !== "object") return null;
  return tb as TitleBlockShape;
}

function pickField(obj: Record<string, unknown>, candidates: string[]): unknown {
  for (const k of candidates) {
    if (Object.hasOwn(obj, k)) return obj[k];
  }
  return undefined;
}

function pickNumberOrString(v: unknown): string | number {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string") return v;
  if (v == null) return "N/A";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  try {
    return JSON.stringify(v);
  } catch {
    return String(v);
  }
}

function jsonOneLine(v: unknown): string {
  try {
    return JSON.stringify(v);
  } catch {
    return String(v);
  }
}

function safeArr(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}

function drawRow(doc: jsPDF, y: number, cells: string[]): void {
  // Simple 4-column layout with fixed x positions.
  const xs = [MARGIN_MM, MARGIN_MM + 50, MARGIN_MM + 100, MARGIN_MM + 130];
  for (let i = 0; i < cells.length; i++) {
    doc.text(cells[i] ?? "", xs[i] ?? MARGIN_MM, y);
  }
}
