"""Compare BriefSpec expected bbox vs actual IFC world bbox.

Reads each brief JSON from src/features/brief-to-ifc/v3/evals/briefs/ and the
matching `*-inspect.json` from forensics/. Writes a markdown summary table to
forensics/brief-vs-actual-summary.md.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


def expected_bbox_from_brief(brief: Dict[str, Any]) -> Tuple[float, float, float]:
    """Best-effort expected world bbox: union of polygon_world_m + bounds_m + element origins."""
    site_bounds = brief.get("site", {}).get("bounds_m") or [0, 0]
    height_limit = brief.get("site", {}).get("height_limit_m") or 0
    xmax = float(site_bounds[0])
    ymax = float(site_bounds[1])
    zmax = float(height_limit)

    # Walk spaces
    for sp in brief.get("spaces", []):
        poly = sp.get("polygon_world_m") or []
        for x, y in poly:
            xmax = max(xmax, float(x))
            ymax = max(ymax, float(y))
        zmax = max(zmax, float(sp.get("height_m") or 0))

    # Walk elements
    for el in brief.get("elements", []):
        ox, oy, oz = el.get("origin_world_m", [0, 0, 0])
        dx, dy, dz = el.get("dims_m", [0, 0, 0])
        xmax = max(xmax, float(ox) + float(dx))
        ymax = max(ymax, float(oy) + float(dy))
        zmax = max(zmax, float(oz) + float(dz))

    return xmax, ymax, zmax


def verdict_for(ratios: Tuple[float, float, float]) -> str:
    """Classify the magnitude of discrepancy."""
    minr = min(r for r in ratios if r > 0) if any(r > 0 for r in ratios) else 0
    if 0.5 <= minr <= 2.0 and all(0.5 <= r <= 2.0 for r in ratios if r > 0):
        return "OK"
    if all(r < 0.01 for r in ratios if r > 0):
        return "MM_INTERPRETED_AS_M"  # actual <<< expected → values stored as m but unit says mm
    if all(r > 100 for r in ratios):
        return "M_INTERPRETED_AS_MM"
    return "MIXED"


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent.parent
    briefs_dir = repo_root / "src/features/brief-to-ifc/v3/evals/briefs"
    forensics_dir = repo_root / "forensics"

    rows = []
    for inspect_path in sorted(forensics_dir.glob("*-inspect.json")):
        stem = inspect_path.stem.replace("-inspect", "")
        brief_path = briefs_dir / f"{stem}.json"
        if not brief_path.exists():
            print(f"skip {stem}: brief not found at {brief_path}")
            continue
        brief = json.loads(brief_path.read_text())
        inspect = json.loads(inspect_path.read_text())
        ex, ey, ez = expected_bbox_from_brief(brief)
        agg = inspect.get("aggregate_world_bbox") or {}
        ax = float(agg.get("xext") or 0)
        ay = float(agg.get("yext") or 0)
        az = float(agg.get("zext") or 0)
        rx = ax / ex if ex > 0 else 0
        ry = ay / ey if ey > 0 else 0
        rz = az / ez if ez > 0 else 0
        v = verdict_for((rx, ry, rz))
        rows.append({
            "brief": stem,
            "expected_xyz": (ex, ey, ez),
            "actual_xyz": (ax, ay, az),
            "ratio_xyz": (rx, ry, rz),
            "verdict": v,
            "length_unit": inspect.get("length_unit", {}).get("label"),
        })

    # Render markdown
    md_lines = [
        "# Brief vs Actual — World Bounding Box Comparison",
        "",
        "Generated by `scripts/forensics/brief-vs-actual.py`. Compares the",
        "expected world bbox from each BriefSpec (union of `site.bounds_m`,",
        "`spaces[].polygon_world_m`, and `elements[].origin_world_m + dims_m`)",
        "against the actual bbox in the on-disk IFC, computed via",
        "`ifcopenshell.geom` with `USE_WORLD_COORDS=True`.",
        "",
        "If the ratio (actual / expected) is consistently ~0.001 → the IFC has",
        "metre-valued coordinates but declares MILLIMETRE units, so viewers",
        "shrink the whole model 1000×.",
        "",
        "| Brief | Expected (x×y×z, m) | Actual (x×y×z, m) | Ratio (x, y, z) | Length Unit | Verdict |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        ex, ey, ez = r["expected_xyz"]
        ax, ay, az = r["actual_xyz"]
        rx, ry, rz = r["ratio_xyz"]
        md_lines.append(
            f"| {r['brief']} | "
            f"{ex:.2f}×{ey:.2f}×{ez:.2f} | "
            f"{ax:.4f}×{ay:.4f}×{az:.4f} | "
            f"{rx:.4f}, {ry:.4f}, {rz:.4f} | "
            f"`{r['length_unit']}` | **{r['verdict']}** |"
        )

    out = forensics_dir / "brief-vs-actual-summary.md"
    out.write_text("\n".join(md_lines) + "\n")
    print(f"wrote {out}")
    for r in rows:
        print(
            f"  {r['brief']:30s} verdict={r['verdict']:25s} "
            f"ratio=({r['ratio_xyz'][0]:.4f}, {r['ratio_xyz'][1]:.4f}, {r['ratio_xyz'][2]:.4f})"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
