/* ─── IFC Enhance — material catalog ──────────────────────────────────────
   Builds a single shared Material per EnhanceTag. IFC meshes tagged with
   the same tag share the same GPU material — fewer state changes, fewer
   GC cycles. Glass is a MeshPhysicalMaterial; textured tags are
   MeshStandardMaterial; everything else is a neutral PBR stub. */

import {
  Color,
  DoubleSide,
  Material,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
  Vector2,
  type WebGLRenderer,
} from "three";
import { loadPBRTextures } from "./texture-loader";
import { PBR_BY_TAG, QUALITY_PRESETS } from "./constants";
import type { EnhanceTag, HDRIPreset, MaterialQuality } from "./types";

export type MaterialCatalog = Map<EnhanceTag, Material>;

/**
 * Build every material we need for Tier 1. Runs in parallel on the texture
 * IO, completes under ~2s on a warm browser cache, ~5–8s cold (20 MB+ of
 * 2k textures across 5 tags).
 *
 * `onProgress(step, progress)` fires as each tag's textures land.
 */
export async function buildMaterialCatalog(
  quality: MaterialQuality,
  litInteriorWindows: boolean,
  hdriPreset: HDRIPreset,
  renderer: WebGLRenderer,
  onProgress?: (step: string, progress: number) => void,
): Promise<MaterialCatalog> {
  const catalog: MaterialCatalog = new Map();
  const qualityCfg = QUALITY_PRESETS[quality];

  const texturedTags = Object.entries(PBR_BY_TAG) as Array<[EnhanceTag, (typeof PBR_BY_TAG)[EnhanceTag]]>;

  let completed = 0;
  const total = texturedTags.length;

  await Promise.all(
    texturedTags.map(async ([tag, spec]) => {
      if (!spec) return;
      onProgress?.(`Loading ${tag}`, completed / total);
      const textures = await loadPBRTextures(spec, quality, renderer);

      /* Baked tiling — UVs are generated by the engine using a box projection
         already scaled by spec.tilingMetres (see tier1-engine), so here we
         don't need texture.repeat.

         Conditional-spread every map key so Three.js never receives an
         explicit `undefined` for an optional parameter (its material-param
         validator warns on undefined; omitting the key is the sanctioned
         way to signal absence). `aoMap` is only attached when quality
         includes AO AND the loader actually returned one; `metalnessMap`
         only when the spec has a metal map AND the loader returned it. */
      const useAOMap = qualityCfg.useAO && Boolean(textures.aoMap);
      const useMetalnessMap = spec.hasMetal && Boolean(textures.metalnessMap);

      const mat = new MeshStandardMaterial({
        roughness: spec.roughness,
        metalness: spec.metalness,
        side: DoubleSide,
        envMapIntensity: 1.0,
        normalScale: new Vector2(1, 1),
        ...(textures.map && { map: textures.map }),
        ...(textures.normalMap && { normalMap: textures.normalMap }),
        ...(textures.roughnessMap && { roughnessMap: textures.roughnessMap }),
        ...(useAOMap && { aoMap: textures.aoMap }),
        ...(useMetalnessMap && { metalnessMap: textures.metalnessMap }),
      });
      if (spec.colorTint) {
        mat.color = new Color(spec.colorTint[0], spec.colorTint[1], spec.colorTint[2]);
      }
      mat.name = `enhance-${tag}`;

      catalog.set(tag, mat);
      completed += 1;
      onProgress?.(`Loaded ${tag}`, completed / total);
    }),
  );

  /* Window glass — fully procedural. The emissive component simulates
     interior lighting visible through the pane; intensity scales with HDRI
     brightness (night → bright glow, day → subtle). */
  const glassEmissiveColor = new Color(0xffd28a);
  const nightBoost = hdriPreset === "night" ? 1 : 0;
  const dayBoost = hdriPreset === "day" ? 0.15 : 0;
  const sunsetBoost = hdriPreset === "sunset" ? 0.4 : 0;
  const overcastBoost = hdriPreset === "overcast" ? 0.2 : 0;
  const emissiveIntensity = litInteriorWindows
    ? (nightBoost ? 0.8 : (sunsetBoost || dayBoost || overcastBoost || 0.15))
    : 0;

  const glass = new MeshPhysicalMaterial({
    color: new Color(0xd4e6f1),
    transparent: true,
    opacity: 0.4,
    transmission: 0.9,
    roughness: 0.05,
    metalness: 0,
    ior: 1.52,
    thickness: 0.5,
    envMapIntensity: 1.5,
    side: DoubleSide,
    emissive: litInteriorWindows ? glassEmissiveColor : new Color(0x000000),
    emissiveIntensity,
    clearcoat: 0.4,
    clearcoatRoughness: 0.05,
  });
  glass.name = "enhance-window-glass";
  catalog.set("window-glass", glass);

  /* Neutral procedural materials for un-textured tags. All PBR but no maps. */
  const neutralSpecs: Partial<Record<EnhanceTag, { color: number; roughness: number; metalness: number }>> = {
    column:  { color: 0xe8e4db, roughness: 0.85, metalness: 0.0 },
    beam:    { color: 0x8a8f96, roughness: 0.4,  metalness: 0.6 },
    stair:   { color: 0xbfb2a0, roughness: 0.75, metalness: 0.0 },
    railing: { color: 0x2d3238, roughness: 0.35, metalness: 0.8 },
    other:   { color: 0xc0c0c8, roughness: 0.8,  metalness: 0.1 },
  };

  for (const [tag, spec] of Object.entries(neutralSpecs) as Array<[EnhanceTag, NonNullable<typeof neutralSpecs[EnhanceTag]>]>) {
    const mat = new MeshStandardMaterial({
      color: new Color(spec.color),
      roughness: spec.roughness,
      metalness: spec.metalness,
      side: DoubleSide,
      envMapIntensity: 1.0,
    });
    mat.name = `enhance-${tag}`;
    catalog.set(tag, mat);
  }

  /* `space` is deliberately absent — engine must NOT swap IFCSPACE meshes. */
  return catalog;
}

/** Dispose every material in the catalog. Textures are cached separately. */
export function disposeMaterialCatalog(catalog: MaterialCatalog): void {
  for (const mat of catalog.values()) mat.dispose();
  catalog.clear();
}
